SetCapsLockState("AlwaysOff")

CapsLock & h:: Send("{Left}")
CapsLock & j:: Send("{Down}")
CapsLock & k:: Send("{Up}")
CapsLock & l:: Send("{Right}")
CapsLock & t:: Send("^{Tab}")

CapsLock & r:: Send("!{Tab}")
CapsLock & z:: Send("^z")
CapsLock & x:: Send("^x")
CapsLock & c:: Send("^c")
CapsLock & v:: Send("^v")
CapsLock & b:: Send("{Backspace}")
CapsLock & d:: Send("^{Left}")
CapsLock & f:: Send("^{Right}")
CapsLock & a:: Send("^a")
CapsLock & p:: Send("^+p")
CapsLock & e:: Send("{Escape}")
CapsLock & n:: Send("{Enter}")

CapsLock & =:: Send("+{=}")
CapsLock & [:: Send("+{[}")
CapsLock & ]:: Send("+{]}")
CapsLock & 9:: Send("+9")
CapsLock & 0:: Send("+0")
CapsLock & -:: Send("+{-}")

CapsLock & s:: Send("{Shift Down}")
CapsLock & s up:: Send("{Shift Up}")
